name: remove-branch-protection

on: workflow_dispatch

env:
  Repos:
    github-branch-api
    
jobs: 
  branch-protection:
    runs-on: ubuntu-latest

    steps:

    #========================================
    # Clean down workspace
    #========================================
    - name: cleaning up previous run
      run: |
        echo "Cleaning up Previous run"
        rm -rf "${{ github.workspace }}/*"

    #===============================================
    # Enabling branch protection to the main branch
    #===============================================
    - name: Remove Branch Protection 
      run: |
        echo "Removing branch protection for main branch"
        for repo in ${{ env.Repos }}; do
          echo "----------------------------------------------"
          echo "Removing branch protection for $repo"
          echo "----------------------------------------------"
          curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.RUNNER_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/j-jagan/$repo/branches/main/protection
        done
        
    #===============================================
    # Clean Down Workspace
    #===============================================
    - name: Clean Down Workspace
      run: |
        echo "Cleaning down workspace"
        rm -rf "${{ github.workspace }}/*"
        
